# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ChurchCRM/box"
  config.vm.box_url = "https://box.churchcrm.io/churchcrm.box"
  config.vm.network "private_network", ip: "192.168.33.21"
  config.vm.hostname = "scotchbox"

   config.vm.provision :shell, :path => "bootstrap.sh"
end
